Update assignment.html
IIITH-Resources/Computer_Programming pull request #6
Opened 2022-02-05 11:55 UTC by gnaneswar-k

Previously upon clicking the link, it was trying to go to index.html within the current directory, which is IIITHResources/CPro/Web (I just used shortforms to represent the actual name.) And this page is nonexistent, so it was showing the error page. But it should actually go to the main homepage, which is two directories up. So I added in the changes for that.

2022-02-05 13:59 UTC, b-beri requested changes
For it, please make it as "index.html". As in different Repos, relative linking is not preferred. And moreover, we have used the convention I have mentioned only in most of the pages, so better to use that only, & if you find some error in it's working then tell me.

2022-02-05 14:02 UTC, b-beri commented
BTW very nice bug hunting. Now you are our official Bug Bounty Program Head.

2022-02-05 16:22 UTC, gnaneswar-k commented
> For it, please make it as "index.html". As in different Repos, relative linking is not preferred. And moreover, we have used the convention I have mentioned only in most of the pages, so better to use that only, & if you find some error in it's working then tell me.

Yeah I just observed how it was in the other pages and kept that type of directory

2022-02-06 05:57 UTC, bhavberi commented
Kindly Once check it again. I have updated it.
If you feel it's ok, then close this PR from your side only.
@gnaneswar-k

2022-02-06 06:05 UTC, closed without merging